apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  my-nginx-config.conf: |
    server {
      listen 80;
      server_name www.kubia-example.com;

      gzip on;
      gzip_types text/plain application/xml;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }

# hoặc có thể config như mẫu sau
#  items:
#           - key: my-nginx-config.conf
#             path: gzip.conf # change name of file from my-nginx-config.conf to gzip.conf
