apiVersion: apps/v1 # change version API
kind: ReplicaSet # change resource name
metadata:
  name: hello-rs
spec:
  replicas: 2
  selector:
    matchLabels: # change here
      app: hello-kube
    # matchExpressions:
    # - key: app
    #   operator: In # Có 4 operators cơ bản là: In, NotIn, Exists, DoesNotExist
    #   values:
    #     - kubia
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
        - image: 080196/hello-kube
          name: hello-kube
          ports:
            - containerPort: 3000
