apiVersion: v1
kind: Service
metadata:
  name: svc1
spec:
  # selecter khai báo các pod mà service chuyển hướng yêu cầu đến
  type: ClusterIP
  ports:
    - name: port1
      port: 80
      targetPort: 80
